default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: mysql2
  pool: 5
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  database: motorhead_4_development

test:
  adapter: mysql2
  pool: 5
  encoding: utf8
  database: motorhead_4_test

production:
  <<: *default
